name: Deploy to Linux Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
        
      - name: Tạo file .env từ GitHub Secrets
        run: |
          cd ~/Development/meomeo
          echo "${{ secrets.ENV_PRODUCTION }}" > server/.env
        
      - name: Deploy with Docker Compose
        run: |
          cd ~/Development/meomeo
          
          # Cập nhật code mới nhất từ git (để đảm bảo không bị lỗi phân nhánh)
          git fetch --all
          git reset --hard origin/main
          
          # Khởi động lại Docker
          docker compose down
          docker compose up -d --build
